# Azure DevOps Pipeline to fetch Code Review Bot from GitHub
# Place this YAML in your target repo to use the bot without copying code

trigger: none
pr:
  branches:
    include:
      - "*"

resources:
  repositories:
    - repository: codeReviewBot
      type: github
      name: har9421/CodeReviewProject
      ref: main
      endpoint: GitHub # Update this to match your service connection name

jobs:
  - job: CodeReview
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - checkout: self
        persistCredentials: true
        clean: true

      - checkout: codeReviewBot
        persistCredentials: true
        clean: true
        # Place under the same 's' sources dir so $(Build.SourcesDirectory)/review-bot exists
        path: s/review-bot

      - script: |
          echo "Build.SourcesDirectory=$(Build.SourcesDirectory)"
          echo "Pipeline.Workspace=$(Pipeline.Workspace)"
          echo "Listing $(Pipeline.Workspace)" && ls -la $(Pipeline.Workspace) || true
          echo "Listing $(Build.SourcesDirectory)" && ls -la $(Build.SourcesDirectory) || true
          echo "Listing $(Pipeline.Workspace)/s" && ls -la $(Pipeline.Workspace)/s || true
          echo "Listing $(Pipeline.Workspace)/s/review-bot" && ls -la $(Pipeline.Workspace)/s/review-bot || true
        displayName: "Diagnostics: show workspace layout"

      - task: NodeTool@0
        inputs:
          versionSpec: "18.x"

      # No local NPM install is required because the bot runs ESLint via npx with a pinned version
      - script: echo "Skipping npm install; using npx eslint@9"
        displayName: "Skip NPM install"

      - task: UseDotNet@2
        inputs:
          packageType: sdk
          version: "8.0.x"

      - script: dotnet build ./src/CodeReviewRunner -c Release
        workingDirectory: $(Pipeline.Workspace)/s/review-bot
        displayName: "Build Code Review Runner"

      - script: dotnet test ./tests/CodeReviewRunner.Tests -c Release --no-build
        workingDirectory: $(Pipeline.Workspace)/s/review-bot
        displayName: "Run bot unit tests"

      - script: |
          RULES="${CODING_STANDARDS_URL:-$(Pipeline.Workspace)/s/review-bot/coding-standards.sample.json}"
          echo "Using rules: $RULES"
          dotnet run --project ./src/CodeReviewRunner \
            "$(Build.SourcesDirectory)" \
            "$RULES" \
            "$(System.PullRequest.PullRequestId)" \
            "$(System.CollectionUri)" \
            "$(System.TeamProject)" \
            "$(Build.Repository.ID)"
        workingDirectory: $(Pipeline.Workspace)/s/review-bot
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
        displayName: "Run Code Review Bot"
