#!/bin/bash

# Azure DevOps PAT Setup Script
# This script helps configure the Azure DevOps Personal Access Token for the Code Review Bot

echo "🔑 Azure DevOps Personal Access Token Setup"
echo "=========================================="
echo ""

# Check if AZURE_DEVOPS_PAT is already set
if [ -n "$AZURE_DEVOPS_PAT" ]; then
    echo "✅ AZURE_DEVOPS_PAT is already set."
    echo "   If you need to change it, unset it first or follow the instructions below."
    echo ""
fi

echo "📋 Azure DevOps PAT Setup Instructions:"
echo ""
echo "1. 🌐 Go to Azure DevOps Token Settings:"
echo "   https://dev.azure.com/khUniverse/_usersSettings/tokens"
echo ""
echo "2. 🔑 Click 'New Token'"
echo ""
echo "3. 📝 Configure your token:"
echo "   - Name: 'CodeReviewBot'"
echo "   - Organization: 'khUniverse'"
echo "   - Expiration: '90 days' (or your preference)"
echo ""
echo "4. ✅ Select these scopes:"
echo "   ☑️  Code (read & write)"
echo "   ☑️  Build (read)"
echo "   ☑️  Project and team (read)"
echo "   ☑️  Work items (read)"
echo ""
echo "5. 🎯 Click 'Create' and copy the token"
echo ""
echo "6. 💾 Choose your setup method:"
echo ""
echo "   Method 1 - Temporary (current session only):"
echo "   export AZURE_DEVOPS_PAT='your-azure-devops-token-here'"
echo ""
echo "   Method 2 - Permanent (add to shell profile):"
echo "   echo 'export AZURE_DEVOPS_PAT=\"your-azure-devops-token-here\"' >> ~/.zshrc"
echo "   source ~/.zshrc"
echo ""
echo "   Method 3 - Environment file (recommended):"
echo "   echo 'AZURE_DEVOPS_PAT=your-azure-devops-token-here' >> .env"
echo "   source .env"
echo ""
echo "7. 🧪 Test your token:"
echo "   curl -u 'khUniverse:\$AZURE_DEVOPS_PAT' https://dev.azure.com/khUniverse/_apis/projects"
echo ""
echo "8. 🚀 Restart the bot:"
echo "   ./stop-all.sh && ./start-intelligent-bot.sh"
echo ""
echo "⚠️  Important Security Notes:"
echo "   - Never commit your token to git"
echo "   - Use .env file and add it to .gitignore"
echo "   - Regenerate token if compromised"
echo "   - Set appropriate expiration date"
echo ""
echo "🔗 Useful Links:"
echo "   - Token Settings: https://dev.azure.com/khUniverse/_usersSettings/tokens"
echo "   - API Documentation: https://docs.microsoft.com/en-us/azure/devops/integrate/"
echo "   - Webhook Setup: https://docs.microsoft.com/en-us/azure/devops/service-hooks/"
